# Generated by Django 3.2 on 2022-02-03 11:36

from django.db import migrations
from django.conf import settings


def add_default_users(apps, schema_editor):
    from apps.users.models import User

    User.objects.create_superuser(
        email=settings.ADMIN_USER_EMAIL,
        password=settings.ADMIN_USER_PASS,
        first_name='Admin',
        last_name='User')

    User.objects.create_user(
        email=settings.DEMO_USER_EMAIL,
        password=settings.DEMO_USER_PASS,
        first_name='Demo',
        last_name='User'
    )


def remove_default_users(apps, schema_editor):
    from apps.users.models import User

    superuser = User.objects.get(first_name='Admin', last_name='User')
    superuser.delete()

    demouser = User.objects.get(first_name='Demo', last_name='User')
    demouser.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_users, remove_default_users)
    ]
