# Generated by Django 3.2 on 2022-02-03 17:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='certified',
            field=models.BooleanField(default=False, verbose_name='Certified'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='consent',
            field=models.BooleanField(default=False, verbose_name='Consent'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='countries',
            field=django_countries.fields.CountryField(default='GB', max_length=746, multiple=True, verbose_name='Operating Countries'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(max_length=150, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='datatypes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('GP', 'Geotagged Photos'), ('DP', 'Drone Photography'), ('GC', 'Ground Control Points'), ('DV', 'Drone Video'), ('DL', 'Drone Lidar'), ('DR', 'Drone Radar'), ('AV', 'Aerial Video'), ('AR', 'Aerial Radar'), ('AL', 'Aerial Lidar'), ('AP', 'Aerial Photo'), ('SP', 'Stereo Photo'), ('OT', 'Other')], max_length=2), default=list, size=None, verbose_name='Datatypes collected'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['email'], name='email_idx'),
        ),
    ]
