# Generated by Django 3.2 on 2022-02-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_add_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='certified',
            field=models.BooleanField(verbose_name='Certified'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='consent',
            field=models.BooleanField(verbose_name='Consent'),
        ),
    ]
