# Generated by Django 3.2 on 2022-02-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_add_user_to_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='created_by',
            field=models.CharField(default='demo@demo.com', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='modified_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
